name: Daily build webhook
on:
  # Triggers the workflow every day at 21:00 GMT
  schedule:
    - cron: "0 21 * * *"

jobs:
 deploy:
    runs-on: ubuntu-18.04
    steps:
      - name: Send webhook to trigger the build
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL  }}
