name: Update package data
on:
  schedule:
    - cron: "0 22 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "verbose"
        type: choice
        options:
          - info
          - verbose
          - debug
      limit:
        description: "Number of projects to process (mainly for debugging, keep the default value of 0 to process everything)"
        required: false
        type: number
        default: 0
jobs:
  update-package-data:
    runs-on: ubuntu-latest
    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - name: Install PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 8.11.0
      - name: Install Dependencies
        shell: bash
        run: pnpm install
      - run: node run cli/tasks/projects/update-package-data.task.js --limit ${{ inputs.limit || 0 }} --loglevel ${{ inputs.logLevel || 'info' }}
        env:
          MONGO_URI_PRODUCTION: ${{ secrets.MONGO_URI_PRODUCTION }}
