name: Update bundle size
on:
  schedule:
    - cron: "0 23 * * *"
  workflow_dispatch:
    inputs:
      logLevel:
        description: "Log level"
        required: true
        default: "verbose"
        type: choice
        options:
          - info
          - verbose
          - debug
      limit:
        required: false
        type: number
        default: 0
      skip:
        required: false
        type: number
        default: 0
jobs:
  update-package-data:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install PNPM
        uses: pnpm/action-setup@v2
        with:
          version: 8.11.0
      - name: Install Dependencies
        shell: bash
        run: pnpm install
      - run: node run cli/tasks/projects/update-bundle-size.task.js --limit ${{ inputs.limit || 0 }} --skip ${{ inputs.skip || 0 }} --loglevel ${{ inputs.logLevel || 'info' }}
        env:
          MONGO_URI_PRODUCTION: ${{ secrets.MONGO_URI_PRODUCTION }}
